require('plugins.nvim-lspconfig')
require('plugins.tree-sitter-manager')
require('plugins.nvim-navic')
require('plugins.lualine')
require('plugins.telescope')
require('plugins.noice')
require('plugins.render-markdown')
require('plugins.mini.snippets')
require('plugins.blink.cmp')
require('plugins.overseer')
require('plugins.comfy-line-numbers')
require('plugins.smear-cursor')
require('plugins.neoscroll')
require('plugins.atone')
require('plugins.conform')
require('plugins.mini.files')
require('plugins.mini.pairs')
-- require('plugins.mini.indentscope')
-- require('plugins.indent-blankline')
require('plugins.mini.starter')
require('plugins.mini.sessions')
require('plugins.mini.align')
require('plugins.colorscheme')
