# Foot theme converted from Kitty Everforest Dark
# Original Kitty theme by @sainnhe

[colors-dark]
alpha=1
background=2d353b
foreground=d3c6aa
flash=e69875
flash-alpha=0.5

## Normal/regular colors (color palette 0-7)
regular0=343f44
regular1=e67e80
regular2=a7c080
regular3=dbbc7f
regular4=7fbbb3
regular5=d699b6
regular6=83c092
regular7=859289

## Bright colors (color palette 8-15)
bright0=868d80
bright1=e67e80
bright2=a7c080
bright3=dbbc7f
bright4=7fbbb3
bright5=d699b6
bright6=83c092
bright7=9da9a0

## Misc colors
selection-foreground=9da9a0
selection-background=505a60

